---
site_name: Rocky Wiki
site_url: https://wiki.rockylinux.org
repo_url: https://github.com/rocky-linux/wiki.rockylinux.org
repo_name: rocky-linux/wiki.rockylinux.org
edit_uri: edit/main/docs/
theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: teal
  highlightjs: true
  hljs_languages:
    - bash
    - python
    - yaml
    - perl
  features:
    - toc.integrate
    - search.suggest
    - search.highlight
    - navigation.top
    - navigation.tabs
    - navigation.indexes
      #- navigation.expand
  logo: assets/icon-white.svg
plugins:
  - autolinks
  - awesome-pages
  - git-revision-date
  - macros:
      include_dir: docs/include
  - search
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - pymdownx.details # this allows collapsible attributions
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
copyright: Copyright &copy; 2022 Rocky Enterprise Software Foundation
...
