---
site_name: Rocky Wiki
site_url: https://wiki.rockylinux.org
repo_url: https://github.com/rocky-linux/wiki.rockylinux.org
repo_name: rocky-linux/wiki.rockylinux.org
edit_uri: edit/main/docs/
theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: teal
  highlightjs: true
  hljs_languages:
    - bash
    - python
    - yaml
    - perl
  features:
    - toc.integrate
    - search.suggest
    - search.highlight
    - navigation.top
    - navigation.tabs
    - navigation.expand

  logo: assets/icon-white.svg
plugins:
  - awesome-pages # this allows hiding of directories from the NAV with build
                  # additionally hides the QA/Testcase_* from the n/p keypress navigation
  - macros:       # this enables includes and macros
      include_dir: docs/include
  - autolinks
  - search
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - toc:
      permalink: true
  - footnotes
  - def_list
  - meta
  - pymdownx.details # this allows collapsible attributions
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
copyright: Copyright &copy; 2021 Rocky Enterprise Software Foundation
...
