---
# Project information
site_name: Rocky Linux Wiki
site_url: https://wiki.rockylinux.org
site_description: >-
  The wiki for the Rocky Linux project

# Repository
repo_url: https://github.com/rocky-linux/wiki.rockylinux.org
repo_name: rocky-linux/wiki.rockylinux.org
edit_uri: edit/main/docs/

# Copyright
copyright: Rocky Enterprise Software Foundation

# Configuration
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  highlightjs: true
  hljs_languages:
    - bash
    - perl
    - python
    - yaml
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.integrate
  logo: assets/icon-white.svg

# Plugins
plugins:
  - autolinks
  - awesome-pages
  - git-revision-date
  - macros:
      include_dir: docs/include
  - search

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - pymdownx.details # this allows collapsible attributions
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
