---
site_name: Rocky Wiki
site_url: https://rocky.shootthej.net
theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: teal
  highlightjs: true
  hljs_languages:
    - bash
    - python
    - yaml
    - perl
  features:
    - toc.integrate
    - search.suggest
    - navigation.top
      #- navigation.tabs
      #- navigation.tabs.sticky
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - toc:
      permalink: true
  - footnotes
  - def_list
  - meta
copyright: Copyright &copy; 2021 Rocky Enterprise Software Foundation
...
